[package]
name = "forge-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
forge-core = { path = "../forge-core" }
forge-domain = { path = "../forge-domain" }
forge-images = { path = "../forge-images" }
forge-profiles = { path = "../forge-profiles" }
forge-state = { path = "../forge-state" }

[lints]
workspace = true
